APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
BASH_SHELLCHECK_ARGUMENTS: --source-path=/tmp/lint
# MegaLinter runs ShellCheck outside the source code directory.
#  `--source-path` has to be set to the value of `DEFAULT_WORKSPACE`.  On
#  GitHub Actions, it has to be set to the value of `GITHUB_WORKSPACE`.
#
# https://megalinter.io/latest/configuration/#common-variables
