version: 2.1

orbs:
  codecov: codecov/codecov@5.0.1

jobs:
  Mega-Linter:
    environment:
      DEFAULT_WORKSPACE: /root/project
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          command: |
            echo 11111111111111111111
            who
            echo "aa $USER bb"
            echo $UID
            pwd
            ls -lA
            head ./scripts/setup-guix.sh
            sudo sh "./scripts/setup-guix.sh"
            ps -ef | grep guix
            # ls -lA $HOME/.guix-profile
            guix pull
            guix install glibc-locales
            . $HOME/.guix-profile/etc/profile
            guix install hello

workflows:
  CI:
    jobs:
      - Mega-Linter
      - test
