version: 2.1

jobs:
  Mega-Linter:
    environment:
      DEFAULT_WORKSPACE: /root/project
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports

workflows:
  CI:
    jobs:
      - Mega-Linter
