version: 2.1

orbs:
  codecov: codecov/codecov@5.0.1

jobs:
  Mega-Linter:
    environment:
      DEFAULT_WORKSPACE: /root/project
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          command: |
            echo 11111111111111111111
            who
            echo "aa $USER bb"
            echo $UID
            GUIX_TEMP_DIR=$(mktemp -d)
            INSTALLER="$GUIX_TEMP_DIR/guix-install.sh"
            curl -o "$INSTALLER" https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
            chmod +x "$INSTALLER"
            "$INSTALLER"
            command -v guix
            guix install hello

workflows:
  CI:
    jobs:
      - Mega-Linter
      - test
